Add json column representation
fslaborg/FsSpreadsheet pull request #94
Opened 2024-06-17 15:49 UTC by HLWeil

2024-06-19 08:36 UTC, Freymaurer requested changes

2024-06-19 08:36 UTC, Freymaurer commented on src/FsSpreadsheet/FsSpreadsheet.fsproj
> +  <ItemGroup />
deleted fable files !!!

2024-06-19 08:40 UTC, Freymaurer commented
did you verify against existing standards? https://spreadsheet.dsl.builders

2024-06-19 11:28 UTC, HLWeil commented
Trying to verify against this example: https://spreadsheet.dsl.builders/#_sheets_and_rows

Encountered some issues. Mostly fixed but one Fable issue remains. Will link it here when I open the Issue there.

2024-06-19 11:38 UTC, HLWeil commented
Should still be mergeable here IMO.

2024-06-21 11:39 UTC, Freymaurer approved these changes

2024-06-27 08:23 UTC, merged